# Generated by Django 5.2.16 on 2026-07-28 16:40

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0002_seed_course_approve_permission'),
        ('content', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RevenueDailyAggregate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('currency', models.CharField(max_length=3)),
                ('gross_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('net_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('computed_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'revenue_daily_aggregates',
                'ordering': ['-period_start'],
                'constraints': [models.UniqueConstraint(fields=('period_start', 'period_end', 'currency'), name='uniq_revenue_period_currency')],
            },
        ),
        migrations.CreateModel(
            name='AnalyticsEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_name', models.CharField(max_length=100)),
                ('session_id', models.CharField(blank=True, default='', max_length=100)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('occurred_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analytics_events', to=settings.AUTH_USER_MODEL)),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analytics_events', to='catalog.course')),
            ],
            options={
                'db_table': 'analytics_events',
                'ordering': ['-occurred_at'],
                'indexes': [models.Index(fields=['event_name', 'occurred_at'], name='analytics_e_event_n_035208_idx')],
            },
        ),
        migrations.CreateModel(
            name='CourseCompletionAggregate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('enrollments_count', models.PositiveIntegerField(default=0)),
                ('completions_count', models.PositiveIntegerField(default=0)),
                ('completion_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('computed_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completion_aggregates', to='catalog.course')),
            ],
            options={
                'db_table': 'course_completion_aggregates',
                'ordering': ['-period_start'],
                'constraints': [models.UniqueConstraint(fields=('course', 'period_start', 'period_end'), name='uniq_completion_course_period')],
            },
        ),
        migrations.CreateModel(
            name='EngagementDailyAggregate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('active_students_count', models.PositiveIntegerField(default=0)),
                ('new_enrollments_count', models.PositiveIntegerField(default=0)),
                ('computed_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='engagement_aggregates', to='catalog.course')),
            ],
            options={
                'db_table': 'engagement_daily_aggregates',
                'ordering': ['-period_start'],
                'constraints': [models.UniqueConstraint(fields=('course', 'period_start', 'period_end'), name='uniq_engagement_course_period')],
            },
        ),
        migrations.CreateModel(
            name='InstructorEarningsAggregate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('gross_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('net_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('computed_at', models.DateTimeField(auto_now=True)),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='earnings_aggregates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'instructor_earnings_aggregates',
                'ordering': ['-period_start'],
                'constraints': [models.UniqueConstraint(fields=('instructor', 'period_start', 'period_end', 'currency'), name='uniq_earnings_instructor_period')],
            },
        ),
        migrations.CreateModel(
            name='LessonDropOffAggregate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('started_count', models.PositiveIntegerField(default=0)),
                ('completed_count', models.PositiveIntegerField(default=0)),
                ('drop_off_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('computed_at', models.DateTimeField(auto_now=True)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drop_off_aggregates', to='content.lesson')),
            ],
            options={
                'db_table': 'lesson_drop_off_aggregates',
                'ordering': ['-period_start'],
                'constraints': [models.UniqueConstraint(fields=('lesson', 'period_start', 'period_end'), name='uniq_dropoff_lesson_period')],
            },
        ),
        migrations.CreateModel(
            name='LessonWatchTimeAggregate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('total_watch_seconds', models.PositiveBigIntegerField(default=0)),
                ('views_count', models.PositiveIntegerField(default=0)),
                ('computed_at', models.DateTimeField(auto_now=True)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watch_time_aggregates', to='content.lesson')),
            ],
            options={
                'db_table': 'lesson_watch_time_aggregates',
                'ordering': ['-period_start'],
                'constraints': [models.UniqueConstraint(fields=('lesson', 'period_start', 'period_end'), name='uniq_watchtime_lesson_period')],
            },
        ),
    ]
