# Generated by Django 5.2.16 on 2026-07-30 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_seed_templates_manage_permission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('message', 'Message'), ('support_ticket', 'Support Ticket'), ('live_session_reminder', 'Live Session Reminder'), ('course_update', 'Course Update'), ('system', 'System')], max_length=30),
        ),
    ]
