# Generated by Django 5.2.16 on 2026-07-28 16:12

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('scope_type', models.CharField(choices=[('platform', 'Platform')], default='platform', max_length=30)),
                ('scope_id', models.UUIDField(blank=True, null=True)),
                ('key', models.CharField(max_length=150)),
                ('value_json', models.JSONField(blank=True, default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'settings',
                'constraints': [models.UniqueConstraint(fields=('scope_type', 'scope_id', 'key'), name='uniq_setting_scope_key')],
            },
        ),
    ]
