# Generated by Django 5.2.16 on 2026-07-30 03:04

import apps.content.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='content_file',
            field=models.FileField(blank=True, upload_to=apps.content.models.lesson_content_upload_path),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='lesson_type',
            field=models.CharField(choices=[('video', 'Video'), ('pdf', 'PDF'), ('article', 'Article'), ('quiz', 'Quiz'), ('assignment', 'Assignment')], default='video', max_length=20),
        ),
    ]
