# Generated by Django 5.2.16 on 2026-07-31 16:52

import apps.content.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_lesson_content_file_alter_lesson_lesson_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='content_file',
            field=models.FileField(blank=True, max_length=255, upload_to=apps.content.models.lesson_content_upload_path),
        ),
    ]
