# Generated by Django 5.2.16 on 2026-08-13 14:12

import apps.content.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0003_lesson_content_file_max_length"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lesson",
            name="content_file",
            field=models.FileField(
                blank=True,
                max_length=255,
                upload_to=apps.content.models.lesson_content_upload_path,
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["mp4", "mov", "m4v", "webm", "pdf"]
                    )
                ],
            ),
        ),
    ]
