# Generated by Django 5.2.16 on 2026-08-15 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0004_alter_lesson_content_file"),
    ]

    operations = [
        migrations.AddField(
            model_name="lesson",
            name="article_body",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="lesson",
            name="video_url",
            field=models.URLField(blank=True, max_length=500),
        ),
    ]
