# Generated by Django 5.2.16 on 2026-07-28 15:46

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0002_seed_course_approve_permission'),
        ('content', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AiChatSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('context_type', models.CharField(choices=[('course_tutor', 'Course Tutor')], default='course_tutor', max_length=30)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ai_chat_sessions', to='catalog.course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_chat_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ai_chat_sessions',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='AiGeneratedContent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content_type', models.CharField(max_length=30)),
                ('source_type', models.CharField(max_length=30)),
                ('source_id', models.UUIDField()),
                ('content_payload', models.JSONField()),
                ('model_used', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('ready', 'Ready')], default='ready', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_generated_content', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ai_generated_content',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AiGenerationJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('job_type', models.CharField(choices=[('summary', 'Summary'), ('quiz', 'Quiz'), ('flashcards', 'Flashcards'), ('transcript', 'Transcript'), ('subtitles', 'Subtitles')], max_length=20)),
                ('source_type', models.CharField(max_length=30)),
                ('source_id', models.UUIDField()),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='queued', max_length=20)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, default='')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_generation_jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ai_generation_jobs',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='AiChatMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('user', 'User'), ('assistant', 'Assistant')], max_length=10)),
                ('content', models.TextField()),
                ('tokens_used', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='ai.aichatsession')),
            ],
            options={
                'db_table': 'ai_chat_messages',
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['session', 'created_at'], name='ai_chat_mes_session_ab267a_idx')],
            },
        ),
        migrations.CreateModel(
            name='Flashcard',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('front_text', models.TextField()),
                ('back_text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flashcards', to='catalog.course')),
                ('generated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generated_flashcards', to=settings.AUTH_USER_MODEL)),
                ('lesson', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='flashcards', to='content.lesson')),
            ],
            options={
                'db_table': 'flashcards',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['course', 'lesson'], name='flashcards_course__6c6233_idx')],
            },
        ),
    ]
