# Generated by Django 5.2.16 on 2026-07-30 03:41

import apps.learning.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certificate',
            name='pdf_key',
        ),
        migrations.AddField(
            model_name='certificate',
            name='pdf_file',
            field=models.FileField(blank=True, upload_to=apps.learning.models.certificate_upload_path),
        ),
    ]
