# Generated by Django 5.2.16 on 2026-07-28 11:59

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('billing_interval', models.CharField(choices=[('monthly', 'Monthly'), ('yearly', 'Yearly')], max_length=10)),
                ('price_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('seat_model', models.CharField(blank=True, max_length=50)),
                ('features_json', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'plans',
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('subscriber_type', models.CharField(choices=[('user', 'User')], default='user', max_length=20)),
                ('subscriber_id', models.UUIDField()),
                ('status', models.CharField(choices=[('active', 'Active'), ('canceled', 'Canceled'), ('expired', 'Expired')], default='active', max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('renews_at', models.DateTimeField(blank=True, null=True)),
                ('canceled_at', models.DateTimeField(blank=True, null=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='billing.plan')),
            ],
            options={
                'db_table': 'subscriptions',
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'active')), fields=('subscriber_type', 'subscriber_id', 'plan'), name='uniq_active_subscription_per_subscriber_plan')],
            },
        ),
    ]
