# Generated by Django 5.2.16 on 2026-07-28 18:55

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DataErasureRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('blocked', 'Blocked')], default='pending', max_length=20)),
                ('block_reason', models.TextField(blank=True, default='')),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='erasure_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'data_erasure_requests',
                'ordering': ['-requested_at'],
            },
        ),
        migrations.CreateModel(
            name='LegalHold',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reason', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('released_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='legal_holds', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'legal_holds',
                'ordering': ['-created_at'],
            },
        ),
    ]
