# Generated by Django 5.2.16 on 2026-08-04 15:00

import apps.hackathons.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Hackathon",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "host_type",
                    models.CharField(
                        choices=[("internal", "Internal"), ("partner", "Partner")],
                        default="internal",
                        max_length=20,
                    ),
                ),
                ("partner_name", models.CharField(blank=True, max_length=200)),
                ("partner_url", models.URLField(blank=True, max_length=500)),
                ("title", models.CharField(max_length=200)),
                ("slug", models.SlugField(blank=True, max_length=220, unique=True)),
                ("summary", models.CharField(blank=True, max_length=500)),
                ("description", models.TextField(blank=True)),
                (
                    "cover_image",
                    models.ImageField(
                        blank=True, upload_to=apps.hackathons.models.hackathon_cover_upload_path
                    ),
                ),
                (
                    "requirements",
                    models.TextField(
                        blank=True, help_text="Eligibility, team, and submission requirements."
                    ),
                ),
                (
                    "prize_summary",
                    models.CharField(
                        blank=True,
                        help_text="Short headline, e.g. '$10,000 in prizes'.",
                        max_length=300,
                    ),
                ),
                ("registration_opens_at", models.DateTimeField(blank=True, null=True)),
                ("registration_deadline", models.DateTimeField()),
                ("submission_deadline", models.DateTimeField()),
                ("starts_at", models.DateTimeField()),
                ("ends_at", models.DateTimeField()),
                ("capacity", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("published", "Published"),
                            ("canceled", "Canceled"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                (
                    "organizer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="organized_hackathons",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "hackathons",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="HackathonRegistration",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("team_name", models.CharField(blank=True, max_length=150)),
                ("motivation", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("registered", "Registered"),
                            ("withdrawn", "Withdrawn"),
                            ("disqualified", "Disqualified"),
                        ],
                        default="registered",
                        max_length=20,
                    ),
                ),
                ("registered_at", models.DateTimeField(auto_now_add=True)),
                (
                    "hackathon",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="registrations",
                        to="hackathons.hackathon",
                    ),
                ),
                (
                    "participant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hackathon_registrations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "hackathon_registrations",
                "ordering": ["-registered_at"],
            },
        ),
        migrations.CreateModel(
            name="HackathonSubmission",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("summary", models.TextField(blank=True)),
                ("repo_url", models.URLField(blank=True, max_length=500)),
                ("demo_url", models.URLField(blank=True, max_length=500)),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
                (
                    "registration",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="submission",
                        to="hackathons.hackathonregistration",
                    ),
                ),
            ],
            options={
                "db_table": "hackathon_submissions",
                "ordering": ["-submitted_at"],
            },
        ),
        migrations.CreateModel(
            name="HackathonWinner",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "placement",
                    models.PositiveSmallIntegerField(help_text="1 = first place, 2 = second, etc."),
                ),
                ("prize_description", models.CharField(blank=True, max_length=300)),
                ("announced_at", models.DateTimeField(auto_now_add=True)),
                (
                    "hackathon",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="winners",
                        to="hackathons.hackathon",
                    ),
                ),
                (
                    "submission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="winner_entries",
                        to="hackathons.hackathonsubmission",
                    ),
                ),
            ],
            options={
                "db_table": "hackathon_winners",
                "ordering": ["placement"],
            },
        ),
        migrations.AddIndex(
            model_name="hackathon",
            index=models.Index(fields=["status", "starts_at"], name="hackathons_status_cc31a4_idx"),
        ),
        migrations.AddIndex(
            model_name="hackathon",
            index=models.Index(fields=["status", "ends_at"], name="hackathons_status_730940_idx"),
        ),
        migrations.AddConstraint(
            model_name="hackathonregistration",
            constraint=models.UniqueConstraint(
                fields=("hackathon", "participant"), name="uniq_registration_hackathon_participant"
            ),
        ),
        migrations.AddConstraint(
            model_name="hackathonwinner",
            constraint=models.UniqueConstraint(
                fields=("hackathon", "placement"), name="uniq_winner_hackathon_placement"
            ),
        ),
        migrations.AddConstraint(
            model_name="hackathonwinner",
            constraint=models.UniqueConstraint(
                fields=("hackathon", "submission"), name="uniq_winner_hackathon_submission"
            ),
        ),
    ]
