# Generated by Django 5.2.16 on 2026-08-13 16:54

import apps.hackathons.models
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hackathons", "0002_seed_hackathons_manage_permission"),
    ]

    operations = [
        migrations.CreateModel(
            name="HackathonGalleryImage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True, upload_to=apps.hackathons.models.hackathon_gallery_upload_path
                    ),
                ),
                ("video_url", models.URLField(blank=True, max_length=500)),
                ("caption", models.CharField(blank=True, max_length=200)),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "hackathon",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gallery_images",
                        to="hackathons.hackathon",
                    ),
                ),
            ],
            options={
                "db_table": "hackathon_gallery_images",
                "ordering": ["sort_order", "uploaded_at"],
            },
        ),
    ]
