# Generated by Django 5.2.16 on 2026-07-30 04:28

import apps.catalog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_seed_course_approve_permission'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='cover_image',
            field=models.ImageField(blank=True, upload_to=apps.catalog.models.course_cover_upload_path),
        ),
    ]
