# Generated by Django 5.2.16 on 2026-07-31 16:38

import django.contrib.postgres.indexes
from django.conf import settings
from django.contrib.postgres.operations import TrigramExtension
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_seed_category_tag_manage_permissions'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # gin_trgm_ops (used by the index below) lives in this extension —
        # needs CREATE EXTENSION privilege on the target DB (available by
        # default on RDS/Cloud SQL/etc. managed Postgres, but not on every
        # restricted hosting setup).
        TrigramExtension(),
        migrations.AddIndex(
            model_name='course',
            index=django.contrib.postgres.indexes.GinIndex(fields=['title', 'summary', 'description'], name='courses_search_trgm_gin', opclasses=['gin_trgm_ops', 'gin_trgm_ops', 'gin_trgm_ops']),
        ),
    ]
