# Generated by Django 5.2.16 on 2026-07-28 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0002_seed_commerce_permissions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='item_type',
            field=models.CharField(choices=[('course', 'Course'), ('plan', 'Plan')], default='course', max_length=20),
        ),
    ]
