# Generated by Django 5.2.16 on 2026-07-28 10:17

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0002_seed_course_approve_permission'),
        ('content', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('single_choice', 'Single choice'), ('multiple_choice', 'Multiple choice')], default='single_choice', max_length=20)),
                ('prompt', models.TextField()),
                ('explanation', models.TextField(blank=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'db_table': 'questions',
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('instructions', models.TextField()),
                ('due_policy', models.JSONField(blank=True, default=dict)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='catalog.course')),
            ],
            options={
                'db_table': 'assignments',
            },
        ),
        migrations.CreateModel(
            name='CodingExercise',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('prompt', models.TextField()),
                ('starter_code', models.TextField(blank=True)),
                ('language', models.CharField(choices=[('python', 'Python 3')], default='python', max_length=20)),
                ('time_limit_ms', models.PositiveIntegerField(default=2000)),
                ('memory_limit_mb', models.PositiveIntegerField(default=256)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coding_exercises', to='catalog.course')),
                ('section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='coding_exercises', to='content.section')),
            ],
            options={
                'db_table': 'coding_exercises',
            },
        ),
        migrations.CreateModel(
            name='CodingExerciseSubmission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_code', models.TextField()),
                ('language', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('passed', 'Passed'), ('failed', 'Failed'), ('error', 'Error')], default='queued', max_length=20)),
                ('score', models.FloatField(blank=True, null=True)),
                ('runtime_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('result_detail', models.JSONField(blank=True, default=list)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('graded_at', models.DateTimeField(blank=True, null=True)),
                ('coding_exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='assessments.codingexercise')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coding_exercise_submissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'coding_exercise_submissions',
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='CodingExerciseTestCase',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('input', models.TextField(blank=True)),
                ('expected_output', models.TextField()),
                ('is_hidden', models.BooleanField(default=True)),
                ('weight', models.PositiveIntegerField(default=1)),
                ('coding_exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_cases', to='assessments.codingexercise')),
            ],
            options={
                'db_table': 'coding_exercise_test_cases',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('text', models.CharField(max_length=500)),
                ('is_correct', models.BooleanField(default=False)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='assessments.question')),
            ],
            options={
                'db_table': 'answers',
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('attempts_allowed', models.PositiveIntegerField(default=1)),
                ('pass_score', models.PositiveIntegerField(default=70)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quizzes', to='catalog.course')),
                ('section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quizzes', to='content.section')),
            ],
            options={
                'db_table': 'quizzes',
            },
        ),
        migrations.AddField(
            model_name='question',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='assessments.quiz'),
        ),
        migrations.CreateModel(
            name='QuizAttempt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('in_progress', 'In progress'), ('submitted', 'Submitted')], default='in_progress', max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('score', models.FloatField(blank=True, null=True)),
                ('passed', models.BooleanField(blank=True, null=True)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='assessments.quiz')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_attempts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'quiz_attempts',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='QuizResponse',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_correct', models.BooleanField(default=False)),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='assessments.quizattempt')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='assessments.question')),
                ('selected_answers', models.ManyToManyField(blank=True, related_name='+', to='assessments.answer')),
            ],
            options={
                'db_table': 'quiz_responses',
            },
        ),
        migrations.CreateModel(
            name='AssignmentSubmission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content_ref', models.TextField()),
                ('grade', models.FloatField(blank=True, null=True)),
                ('feedback', models.TextField(blank=True)),
                ('graded_at', models.DateTimeField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='assessments.assignment')),
                ('graded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='graded_assignment_submissions', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignment_submissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'assignment_submissions',
                'constraints': [models.UniqueConstraint(fields=('assignment', 'student'), name='uniq_submission_per_student')],
            },
        ),
        migrations.AddConstraint(
            model_name='quizattempt',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'in_progress')), fields=('quiz', 'student'), name='uniq_in_progress_attempt_per_student'),
        ),
        migrations.AddConstraint(
            model_name='quizresponse',
            constraint=models.UniqueConstraint(fields=('attempt', 'question'), name='uniq_response_per_question'),
        ),
    ]
