# Generated by Django 5.2.16 on 2026-07-28 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignmentsubmission',
            name='ai_suggested_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assignmentsubmission',
            name='ai_suggested_feedback',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='assignmentsubmission',
            name='ai_suggested_grade',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
