# Generated by Django 5.2.16 on 2026-07-28 09:30

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0002_seed_course_approve_permission'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConferencingAccount',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider', models.CharField(choices=[('zoom', 'Zoom'), ('google_meet', 'Google Meet')], max_length=20)),
                ('external_account_id', models.CharField(blank=True, max_length=255)),
                ('access_token_encrypted', models.TextField()),
                ('refresh_token_encrypted', models.TextField(blank=True)),
                ('token_expires_at', models.DateTimeField(blank=True, null=True)),
                ('connected_at', models.DateTimeField(auto_now_add=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conferencing_accounts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'conferencing_accounts',
            },
        ),
        migrations.CreateModel(
            name='LiveSession',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider', models.CharField(choices=[('zoom', 'Zoom'), ('google_meet', 'Google Meet')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('scheduled_start_at', models.DateTimeField()),
                ('scheduled_end_at', models.DateTimeField()),
                ('timezone', models.CharField(default='UTC', max_length=50)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('live', 'Live'), ('ended', 'Ended'), ('canceled', 'Canceled')], default='scheduled', max_length=20)),
                ('capacity', models.PositiveIntegerField(blank=True, null=True)),
                ('external_meeting_id', models.CharField(blank=True, max_length=255)),
                ('join_url', models.URLField(blank=True, max_length=1000)),
                ('host_join_url', models.URLField(blank=True, max_length=1000)),
                ('is_recorded', models.BooleanField(default=True)),
                ('conferencing_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='live_sessions', to='live_sessions.conferencingaccount')),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='live_sessions', to='catalog.course')),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='hosted_live_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'live_sessions',
                'ordering': ['scheduled_start_at'],
            },
        ),
        migrations.CreateModel(
            name='LiveSessionRecording',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider_recording_id', models.CharField(blank=True, max_length=255)),
                ('playback_url', models.URLField(blank=True, max_length=1000)),
                ('download_key', models.CharField(blank=True, max_length=500)),
                ('duration_seconds', models.PositiveIntegerField(default=0)),
                ('available_at', models.DateTimeField(blank=True, null=True)),
                ('live_session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='recording', to='live_sessions.livesession')),
            ],
            options={
                'db_table': 'live_session_recordings',
            },
        ),
        migrations.CreateModel(
            name='LiveSessionRegistration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('registered', 'Registered'), ('attended', 'Attended'), ('no_show', 'No-show'), ('canceled', 'Canceled')], default='registered', max_length=20)),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
                ('joined_at', models.DateTimeField(blank=True, null=True)),
                ('left_at', models.DateTimeField(blank=True, null=True)),
                ('attended_duration_seconds', models.PositiveIntegerField(default=0)),
                ('live_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='live_sessions.livesession')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='live_session_registrations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'live_session_registrations',
            },
        ),
        migrations.AddConstraint(
            model_name='conferencingaccount',
            constraint=models.UniqueConstraint(condition=models.Q(('revoked_at__isnull', True)), fields=('user', 'provider'), name='uniq_active_conferencing_account_per_provider'),
        ),
        migrations.AddIndex(
            model_name='livesession',
            index=models.Index(fields=['course', 'scheduled_start_at'], name='live_sessio_course__324863_idx'),
        ),
        migrations.AddConstraint(
            model_name='livesessionregistration',
            constraint=models.UniqueConstraint(fields=('live_session', 'student'), name='uniq_registration_session_student'),
        ),
    ]
