# Generated by Django 5.2.16 on 2026-07-28 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('live_sessions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='livesessionregistration',
            name='reminded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
