# Generated by Django 5.2.16 on 2026-07-27 22:31

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0002_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='MFAFactor',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('factor_type', models.CharField(choices=[('totp', 'TOTP')], default='totp', max_length=20)),
                ('secret_encrypted', models.TextField()),
                ('is_primary', models.BooleanField(default=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mfa_factors', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'mfa_factors',
            },
        ),
        migrations.CreateModel(
            name='OAuthIdentity',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider', models.CharField(choices=[('google', 'Google'), ('apple', 'Apple'), ('facebook', 'Facebook')], max_length=20)),
                ('provider_user_id', models.CharField(max_length=255)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='oauth_identities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'oauth_identities',
                'constraints': [models.UniqueConstraint(fields=('provider', 'provider_user_id'), name='uniq_oauth_provider_identity')],
            },
        ),
    ]
