# Generated by Django 5.2.16 on 2026-07-30 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0004_seed_users_manage_permission'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='github_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='linkedin_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='twitter_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='website_url',
            field=models.URLField(blank=True),
        ),
    ]
