# Generated by Django 5.2.16 on 2026-07-30 15:12

import apps.identity.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0005_profile_github_url_profile_linkedin_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='avatar_url',
        ),
        migrations.AddField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, upload_to=apps.identity.models.profile_avatar_upload_path),
        ),
        migrations.AddField(
            model_name='profile',
            name='bio',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='youtube_url',
            field=models.URLField(blank=True),
        ),
    ]
