"""
Contract tests generated straight from docs/03-api/02-openapi.yaml, run
against the real Django app (via DRF's APIClient, the same client every
other test in this suite uses) with request data generated by
schemathesis/Hypothesis from the spec's own parameter/schema definitions.

Scoped deliberately to the public, unauthenticated, state-independent GET
endpoints only (course/category/tag/plan browsing). Exercising the ~150
other (mostly authenticated, resource-owning) operations for real would
need seeded fixtures per operation — valid JWTs, pre-existing courses/
orders/enrollments owned by the calling user, etc. — a much larger effort
than a documentation-freeze contract-test smoke pass. This is a real,
currently-running check, not a stub: it caught a genuine spec bug before
this commit landed — several of these routes were missing `security: []`
even though the real views are AllowAny, which this test surfaced as a
"the API accepted a request the spec claims requires auth" failure (see
the security: [] additions elsewhere in this commit).

Not using schemathesis's own `case.call()` / `case.validate_response()`:
those assume a `requests`/`httpx`/werkzeug-shaped response, and calling
Django's real WSGI handler directly (rather than through Django's test
Client) triggers Django's production "close the DB connection at the end
of every request" signal handling, which fights pytest-django's
single-connection-per-test wrapping. Building the request from the
schemathesis-generated Case and dispatching it through APIClient sidesteps
that entirely, at the cost of checking status-code conformance manually
instead of getting schemathesis's full built-in check suite for free.
"""

from pathlib import Path
from urllib.parse import urlencode

import django
import pytest
import schemathesis
from hypothesis import find
from rest_framework.test import APIClient

pytestmark = pytest.mark.django_db

SPEC_PATH = Path(__file__).resolve().parents[3] / "docs" / "03-api" / "02-openapi.yaml"

django.setup()
_schema = schemathesis.openapi.from_path(SPEC_PATH)

_PUBLIC_READ_PATHS = ["/categories", "/tags", "/plans", "/courses"]


def _public_read_operations():
    operations = []
    for result in _schema.get_all_operations():
        operation = result.ok()
        if operation.method.upper() == "GET" and operation.path in _PUBLIC_READ_PATHS:
            operations.append(operation)
    return operations


@pytest.mark.parametrize(
    "operation", _public_read_operations(), ids=lambda op: f"{op.method} {op.path}"
)
def test_public_read_endpoint_matches_spec(operation):
    case = find(operation.as_strategy(), lambda c: True)

    # case.path is relative to the spec's `servers:` entry (base_path,
    # "/api/v1/"); docs/03-api/02-openapi.yaml also omits trailing slashes
    # for readability, but every real Django route requires one.
    full_path = f"{_schema.base_path.rstrip('/')}{case.path}"
    path = full_path if full_path.endswith("/") else f"{full_path}/"
    if case.query:
        path = f"{path}?{urlencode(case.query, doseq=True)}"

    response = APIClient().get(path)

    documented_codes = set(operation.definition.raw.get("responses", {}))
    assert str(response.status_code) in documented_codes, (
        f"{operation.method} {operation.path} returned {response.status_code}, "
        f"which docs/03-api/02-openapi.yaml doesn't document (documented: "
        f"{sorted(documented_codes)}). Example query: {case.query!r}"
    )
